language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
matrix:
  include:
    - rvm: 2.2
      os: osx
      osx_image: xcode7.3
dist: trusty
sudo: true
before_install:
  - gem install bundler -v 1.12.0
